// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_perfectionist_5 = "CgkIk_u-oIMHEAIQBw"; // <GPGSID>
        public const string achievement_the_intouchable_100 = "CgkIk_u-oIMHEAIQFQ"; // <GPGSID>
        public const string achievement_kittyz_rush_10 = "CgkIk_u-oIMHEAIQAg"; // <GPGSID>
        public const string achievement_why_are_you_so_angry = "CgkIk_u-oIMHEAIQGw"; // <GPGSID>
        public const string achievement_perseverant = "CgkIk_u-oIMHEAIQGQ"; // <GPGSID>
        public const string achievement_teamwork = "CgkIk_u-oIMHEAIQEQ"; // <GPGSID>
        public const string achievement_the_intouchable_50 = "CgkIk_u-oIMHEAIQFA"; // <GPGSID>
        public const string achievement_childs_play = "CgkIk_u-oIMHEAIQDw"; // <GPGSID>
        public const string achievement_nigthmare = "CgkIk_u-oIMHEAIQDg"; // <GPGSID>
        public const string achievement_bring_the_ball_1 = "CgkIk_u-oIMHEAIQCg"; // <GPGSID>
        public const string achievement_the_intouchable_25 = "CgkIk_u-oIMHEAIQEw"; // <GPGSID>
        public const string achievement_support_the_animal_cause = "CgkIk_u-oIMHEAIQDQ"; // <GPGSID>
        public const string achievement_nosy = "CgkIk_u-oIMHEAIQDA"; // <GPGSID>
        public const string achievement_bring_the_ball_10 = "CgkIk_u-oIMHEAIQFg"; // <GPGSID>
        public const string achievement_dont_claim_victory_too_quickly = "CgkIk_u-oIMHEAIQEA"; // <GPGSID>
        public const string achievement_this_game_is_too_hard_for_me = "CgkIk_u-oIMHEAIQGg"; // <GPGSID>
        public const string achievement_im_freeee = "CgkIk_u-oIMHEAIQCw"; // <GPGSID>
        public const string achievement_kittyz_rush_1000 = "CgkIk_u-oIMHEAIQBQ"; // <GPGSID>
        public const string achievement_perfectionist_20 = "CgkIk_u-oIMHEAIQCQ"; // <GPGSID>
        public const string achievement_kittyz_rush_500 = "CgkIk_u-oIMHEAIQBA"; // <GPGSID>
        public const string achievement_bring_the_ball_100 = "CgkIk_u-oIMHEAIQGA"; // <GPGSID>
        public const string achievement_the_intouchable_5 = "CgkIk_u-oIMHEAIQEg"; // <GPGSID>
        public const string achievement_bring_the_ball_50 = "CgkIk_u-oIMHEAIQFw"; // <GPGSID>
        public const string achievement_kittyz_rush_100 = "CgkIk_u-oIMHEAIQAw"; // <GPGSID>
        public const string achievement_perfectionist_10 = "CgkIk_u-oIMHEAIQCA"; // <GPGSID>
        public const string leaderboard_overall_score = "CgkIk_u-oIMHEAIQAQ"; // <GPGSID>
        public const string achievement_perfectionist_1 = "CgkIk_u-oIMHEAIQBg"; // <GPGSID>

}

